name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build, Lint, and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Lint Code with SuperLinter
      uses: github/super-linter@v5
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LANGUAGES: csharp
        VALIDATE_ALL_CODEBASE: true
        RUN_LOCAL: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore Dependencies
      run: dotnet restore TDD_dpp/TDD_dpp.sln

    - name: Build Solution
      run: dotnet build TDD_dpp/TDD_dpp.sln --configuration Release

    - name: Run Tests with Coverage
      run: |
        dotnet test TDD_dpp/TDD_dpp.Tests/TDD_dpp.Tests.csproj --configuration Release --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=TestResults.trx"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.cobertura.xml
